# Site settings
title: "Wasim Thabraze"
description: > 
  Hi, I'm Wasim. Here, I mainly write about Golang, Open source and random ruminations on programming and infrastructure.

author: Wasim Thabraze
email: wasim@thabraze.me
twitter_username: imwaseem18
github_username: waseem18

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thabraze.me" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

